/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;
import Model.Task;
import java.awt.Dimension;
import db.UserDAO;
import javax.swing.JOptionPane;
import db.TaskDAO;
import Controller.BoardController;
import Model.User;
/**
 *
 * @author Kiwit
 */
public class AddTaskDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddTaskDialog.class.getName());
    private Task currentTask;
    /**
     * Creates new form TaskDetailDialog
     */
    public AddTaskDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Dimension fixedSize = new Dimension(400, 400); 
        populateUserComboBox();
        this.getContentPane().requestFocusInWindow(); //stop the focus being on the first input field
         this.setMinimumSize(fixedSize);
         this.setPreferredSize(fixedSize);
         this.setMaximumSize(fixedSize);
         UserDAO userDao = new UserDAO();
         
        

        
    
    }
    
    public void populateUserComboBox() {
    
    db.UserDAO userDao = new db.UserDAO();
    
    // Fetch the list of users from SQLite
    java.util.List<Model.User> users = userDao.getAllUsers();
    
    //clear existing items to prevent duplicates if refreshed
     assignedUserDropDown.removeAllItems();
    
     //creating user object to add as the select user option to the drop down
    Model.User prompt = new Model.User();
    prompt.setUserName("Select User...");
    prompt.setUserID(-1); // -1 so it is not mistaken as a real user
    
    assignedUserDropDown.addItem(prompt);
    
    //through and add them to the dropdown
    for (Model.User u : users) {
       //add user name to dropdown
       assignedUserDropDown.addItem(u); 
     
    }
}
    
    private boolean validateInputs() {
    String name = taskNameField.getText().trim();
    String description = descriptionTxtArea.getText().trim();
    String dateStr = dueDateField.getText().trim();
    Object selectedUser = assignedUserDropDown.getSelectedItem();

    //Task Name Validation (Not empty, not placeholder, max 50 chars)
    if (name.isEmpty() || name.equals("Enter Task Name (Max 50 chars)")) {
        showError("Task name cannot be empty.");
        return false;
    }
    if (name.length() > 50) {
        showError("Task name must be 50 characters or less.");
        return false;
    }

    // User Selection Validation
   if (!(selectedUser instanceof User) || ((User)selectedUser).getUserID() == -1) {
            showError("Please select a valid user.");
            return false;
        }

    // Date Format Validation (dd-mm-yyyy)
    if (!dateStr.matches("\\d{2}-\\d{2}-\\d{4}")) {
        showError("Date must be in the format dd-mm-yyyy (e.g., 06-05-2026).");
        return false;
    }

    // Description Validation (Max 200 chars)
    if (description.length() > 200) {
        showError("Description must be 200 characters or less.");
        return false;
    }

    return true; // All checks passed
}

   // Helper method to keep code clean
   private void showError(String message) {
    javax.swing.JOptionPane.showMessageDialog(this, message, "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        TaskName = new javax.swing.JLabel();
        TaskDetailGrid = new javax.swing.JPanel();
        taskName = new javax.swing.JLabel();
        taskNameField = new javax.swing.JTextField();
        owner = new javax.swing.JLabel();
        ownerField = new javax.swing.JLabel();
        assignedLabel = new javax.swing.JLabel();
        assignedUserDropDown = new javax.swing.JComboBox<>();
        dueDateLabel = new javax.swing.JLabel();
        dueDateField = new javax.swing.JTextField();
        description = new javax.swing.JLabel();
        scrollPaneTxtArea = new javax.swing.JScrollPane();
        descriptionTxtArea = new javax.swing.JTextArea();
        btnContainer = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setModal(true);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        Main.setLayout(new java.awt.BorderLayout());

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));
        TopPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        TopPanel.setLayout(new java.awt.BorderLayout());

        TaskName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TaskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskName.setText("Add Task");
        TaskName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TaskName.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        TopPanel.add(TaskName, java.awt.BorderLayout.CENTER);

        Main.add(TopPanel, java.awt.BorderLayout.PAGE_START);

        TaskDetailGrid.setBackground(new java.awt.Color(255, 255, 255));
        TaskDetailGrid.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        TaskDetailGrid.setMaximumSize(new java.awt.Dimension(400, 400));
        TaskDetailGrid.setLayout(new java.awt.GridLayout(5, 2, 10, 2));

        taskName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        taskName.setText("Task Name *");
        TaskDetailGrid.add(taskName);

        taskNameField.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        taskNameField.setForeground(new java.awt.Color(204, 204, 204));
        taskNameField.setText("Enter Task Name (Max 50 chars) ");
        taskNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taskNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                taskNameFieldFocusLost(evt);
            }
        });
        taskNameField.addActionListener(this::taskNameFieldActionPerformed);
        TaskDetailGrid.add(taskNameField);

        owner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        owner.setText("Onwer");
        TaskDetailGrid.add(owner);

        ownerField.setText("Mitchell Travis");
        TaskDetailGrid.add(ownerField);

        assignedLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        assignedLabel.setText("Assigned");
        TaskDetailGrid.add(assignedLabel);

        TaskDetailGrid.add(assignedUserDropDown);

        dueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dueDateLabel.setText("Due Date:");
        TaskDetailGrid.add(dueDateLabel);

        dueDateField.setForeground(new java.awt.Color(204, 204, 204));
        dueDateField.setText("dd-mm-yyyy");
        dueDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dueDateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dueDateFieldFocusLost(evt);
            }
        });
        TaskDetailGrid.add(dueDateField);

        description.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        description.setText("Description: ");
        TaskDetailGrid.add(description);

        descriptionTxtArea.setColumns(20);
        descriptionTxtArea.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        descriptionTxtArea.setForeground(new java.awt.Color(204, 204, 204));
        descriptionTxtArea.setRows(5);
        descriptionTxtArea.setText("Add description (Max 200 chars)");
        descriptionTxtArea.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descriptionTxtAreaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descriptionTxtAreaFocusLost(evt);
            }
        });
        scrollPaneTxtArea.setViewportView(descriptionTxtArea);

        TaskDetailGrid.add(scrollPaneTxtArea);

        Main.add(TaskDetailGrid, java.awt.BorderLayout.CENTER);

        btnContainer.setBackground(new java.awt.Color(255, 255, 255));

        saveBtn.setBackground(new java.awt.Color(0, 102, 255));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        saveBtn.setMinimumSize(new java.awt.Dimension(45, 23));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
        });
        btnContainer.add(saveBtn);

        cancelBtn.setBackground(new java.awt.Color(0, 102, 255));
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(this::cancelBtnActionPerformed);
        btnContainer.add(cancelBtn);

        Main.add(btnContainer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
                 this.dispose();  //close this window
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        
        if(validateInputs()){
        //retrieve values from the input fields
        String name = taskNameField.getText().trim();
        String desc = descriptionTxtArea.getText().trim();
        String date = dueDateField.getText().trim();
        User selectedUser = (Model.User) assignedUserDropDown.getSelectedItem();
        Task newTask = new Task();
        newTask.setTaskName(name);
        newTask.setTaskDescription(desc);
        newTask.setDueDate(date);
        newTask.setAssignedUser(selectedUser.getUserID());
        newTask.setSwimlane("standard"); //start new tasks in the standard swimlane
        newTask.setColumnID(1); //start new tasks in the requested column
        BoardController.instance.handleAddTask(newTask);
        this.dispose();
        }
    }//GEN-LAST:event_saveBtnMouseClicked

    private void taskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taskNameFieldActionPerformed

    private void taskNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskNameFieldFocusGained
        // TODO add your handling code here:
        if (taskNameField.getText().equals("Enter Task Name (Max 50 chars) ")) {
            taskNameField.setText("");
            taskNameField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
            taskNameField.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_taskNameFieldFocusGained

    private void taskNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taskNameFieldFocusLost
        // TODO add your handling code here:
        if (taskNameField.getText().isEmpty()) {
            taskNameField.setForeground(java.awt.Color.GRAY);
            taskNameField.setText("Enter Task Name (Max 50 chars) ");
        }
    }//GEN-LAST:event_taskNameFieldFocusLost

    private void dueDateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dueDateFieldFocusGained
        // TODO add your handling code here:
        if (dueDateField.getText().equals("dd-mm-yyyy")) {
            dueDateField.setText("");
            dueDateField.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
            dueDateField.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_dueDateFieldFocusGained

    private void dueDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dueDateFieldFocusLost
        // TODO add your handling code here:
         if (dueDateField.getText().isEmpty()) {
            dueDateField.setForeground(java.awt.Color.GRAY);
            dueDateField.setText("dd-mm-yyyy");
        }
    }//GEN-LAST:event_dueDateFieldFocusLost

    private void descriptionTxtAreaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTxtAreaFocusGained
        // TODO add your handling code here:
        if (descriptionTxtArea.getText().equals("Add description (Max 200 chars)")) {
            descriptionTxtArea.setText("");
            descriptionTxtArea.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
            descriptionTxtArea.setForeground(java.awt.Color.BLACK);
        }
    }//GEN-LAST:event_descriptionTxtAreaFocusGained

    private void descriptionTxtAreaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descriptionTxtAreaFocusLost
        // TODO add your handling code here:
         if (descriptionTxtArea.getText().isEmpty()) {
            descriptionTxtArea.setForeground(java.awt.Color.GRAY);
            descriptionTxtArea.setText("Add description (Max 200 chars)");
        }
    }//GEN-LAST:event_descriptionTxtAreaFocusLost

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JPanel TaskDetailGrid;
    private javax.swing.JLabel TaskName;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel assignedLabel;
    private javax.swing.JComboBox<Model.User> assignedUserDropDown;
    private javax.swing.JPanel btnContainer;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionTxtArea;
    private javax.swing.JTextField dueDateField;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JLabel owner;
    private javax.swing.JLabel ownerField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JScrollPane scrollPaneTxtArea;
    private javax.swing.JLabel taskName;
    private javax.swing.JTextField taskNameField;
    // End of variables declaration//GEN-END:variables
}
