package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Kiwit
 */
public class MainBoard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainBoard.class.getName());

    /**
     * Creates new form MainBoard
     */
    public MainBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        centerContainer = new javax.swing.JPanel();
        panelGridHeadings = new javax.swing.JPanel();
        requestedHeading = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inprogressHeading = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        completeHeading = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelGridTaskContainers = new javax.swing.JPanel();
        todoContainer = new javax.swing.JPanel();
        inprogressContainer = new javax.swing.JPanel();
        completeContainer = new javax.swing.JPanel();
        ExpediteSection = new javax.swing.JPanel();
        expediteHeading = new javax.swing.JPanel();
        expediteLabel = new javax.swing.JLabel();
        expediteGrid = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        topPanel.setOpaque(false);
        topPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kanban Board");
        topPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add Task");
        topPanel.add(jButton1, java.awt.BorderLayout.LINE_END);

        bodyPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerContainer.setBackground(new java.awt.Color(255, 255, 255));
        centerContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        centerContainer.setMaximumSize(new java.awt.Dimension(2147483647, 1000));
        centerContainer.setLayout(new java.awt.BorderLayout());

        panelGridHeadings.setBackground(new java.awt.Color(255, 255, 255));
        panelGridHeadings.setMaximumSize(new java.awt.Dimension(32767, 35));
        panelGridHeadings.setPreferredSize(new java.awt.Dimension(423, 35));
        panelGridHeadings.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        requestedHeading.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("REQUESTED");

        javax.swing.GroupLayout requestedHeadingLayout = new javax.swing.GroupLayout(requestedHeading);
        requestedHeading.setLayout(requestedHeadingLayout);
        requestedHeadingLayout.setHorizontalGroup(
            requestedHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(requestedHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(requestedHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        requestedHeadingLayout.setVerticalGroup(
            requestedHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(requestedHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(requestedHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelGridHeadings.add(requestedHeading);

        inprogressHeading.setBackground(new java.awt.Color(255, 153, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IN PROGRESS");

        javax.swing.GroupLayout inprogressHeadingLayout = new javax.swing.GroupLayout(inprogressHeading);
        inprogressHeading.setLayout(inprogressHeadingLayout);
        inprogressHeadingLayout.setHorizontalGroup(
            inprogressHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(inprogressHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inprogressHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        inprogressHeadingLayout.setVerticalGroup(
            inprogressHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(inprogressHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(inprogressHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelGridHeadings.add(inprogressHeading);

        completeHeading.setBackground(new java.awt.Color(0, 204, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("DONE");

        javax.swing.GroupLayout completeHeadingLayout = new javax.swing.GroupLayout(completeHeading);
        completeHeading.setLayout(completeHeadingLayout);
        completeHeadingLayout.setHorizontalGroup(
            completeHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(completeHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(completeHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        completeHeadingLayout.setVerticalGroup(
            completeHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(completeHeadingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(completeHeadingLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelGridHeadings.add(completeHeading);

        centerContainer.add(panelGridHeadings, java.awt.BorderLayout.NORTH);

        panelGridTaskContainers.setBackground(new java.awt.Color(255, 255, 255));
        panelGridTaskContainers.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        todoContainer.setBackground(new java.awt.Color(255, 255, 255));
        todoContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout todoContainerLayout = new javax.swing.GroupLayout(todoContainer);
        todoContainer.setLayout(todoContainerLayout);
        todoContainerLayout.setHorizontalGroup(
            todoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        todoContainerLayout.setVerticalGroup(
            todoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelGridTaskContainers.add(todoContainer);

        inprogressContainer.setBackground(new java.awt.Color(255, 255, 255));
        inprogressContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout inprogressContainerLayout = new javax.swing.GroupLayout(inprogressContainer);
        inprogressContainer.setLayout(inprogressContainerLayout);
        inprogressContainerLayout.setHorizontalGroup(
            inprogressContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        inprogressContainerLayout.setVerticalGroup(
            inprogressContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelGridTaskContainers.add(inprogressContainer);

        completeContainer.setBackground(new java.awt.Color(255, 255, 255));
        completeContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout completeContainerLayout = new javax.swing.GroupLayout(completeContainer);
        completeContainer.setLayout(completeContainerLayout);
        completeContainerLayout.setHorizontalGroup(
            completeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        completeContainerLayout.setVerticalGroup(
            completeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        panelGridTaskContainers.add(completeContainer);

        centerContainer.add(panelGridTaskContainers, java.awt.BorderLayout.CENTER);

        ExpediteSection.setBackground(new java.awt.Color(204, 204, 204));
        ExpediteSection.setForeground(new java.awt.Color(255, 255, 255));
        ExpediteSection.setMaximumSize(new java.awt.Dimension(32767, 35));
        ExpediteSection.setLayout(new java.awt.BorderLayout());

        expediteHeading.setBackground(new java.awt.Color(255, 51, 51));
        expediteHeading.setMaximumSize(new java.awt.Dimension(32767, 35));
        expediteHeading.setLayout(new java.awt.BorderLayout());

        expediteLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        expediteLabel.setForeground(new java.awt.Color(255, 255, 255));
        expediteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        expediteLabel.setText("Expedite");
        expediteLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        expediteHeading.add(expediteLabel, java.awt.BorderLayout.CENTER);

        ExpediteSection.add(expediteHeading, java.awt.BorderLayout.PAGE_START);

        expediteGrid.setBackground(new java.awt.Color(255, 255, 255));
        expediteGrid.setLayout(new java.awt.GridLayout(1, 3, 15, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        expediteGrid.add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        expediteGrid.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        expediteGrid.add(jPanel3);

        ExpediteSection.add(expediteGrid, java.awt.BorderLayout.CENTER);

        centerContainer.add(ExpediteSection, java.awt.BorderLayout.PAGE_END);

        bodyPanel.add(centerContainer, java.awt.BorderLayout.CENTER);

        getContentPane().add(bodyPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainBoard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExpediteSection;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel centerContainer;
    private javax.swing.JPanel completeContainer;
    private javax.swing.JPanel completeHeading;
    private javax.swing.JPanel expediteGrid;
    private javax.swing.JPanel expediteHeading;
    private javax.swing.JLabel expediteLabel;
    private javax.swing.JPanel inprogressContainer;
    private javax.swing.JPanel inprogressHeading;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelGridHeadings;
    private javax.swing.JPanel panelGridTaskContainers;
    private javax.swing.JPanel requestedHeading;
    private javax.swing.JPanel todoContainer;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
