/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author Kiwit
 */
public class taskCard extends javax.swing.JPanel {

    /**
     * Creates new form taskCard
     */
    public taskCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskNamePanel = new javax.swing.JPanel();
        taskName = new javax.swing.JLabel();
        taskDetailGridHolder = new javax.swing.JPanel();
        taskDetailGrid = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnTextHolder = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(2147483647, 250));
        setPreferredSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.BorderLayout());

        taskNamePanel.setBackground(new java.awt.Color(255, 255, 255));
        taskNamePanel.setLayout(new java.awt.BorderLayout());

        taskName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskName.setText("Task Name");
        taskName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        taskNamePanel.add(taskName, java.awt.BorderLayout.CENTER);

        add(taskNamePanel, java.awt.BorderLayout.NORTH);

        taskDetailGridHolder.setBackground(new java.awt.Color(255, 255, 255));
        taskDetailGridHolder.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        taskDetailGridHolder.setLayout(new java.awt.BorderLayout());

        taskDetailGrid.setBackground(new java.awt.Color(255, 255, 255));
        taskDetailGrid.setLayout(new java.awt.GridLayout(4, 1));

        jLabel1.setText("Owner: F.Name L.Name");
        taskDetailGrid.add(jLabel1);

        jLabel2.setText("Assigned: F.Name L.Name");
        taskDetailGrid.add(jLabel2);

        btnTextHolder.setBackground(new java.awt.Color(255, 255, 255));
        btnTextHolder.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jLabel3.setText("Date: 00/00/0000");
        btnTextHolder.add(jLabel3);

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete");
        btnTextHolder.add(jButton1);

        taskDetailGrid.add(btnTextHolder);

        taskDetailGridHolder.add(taskDetailGrid, java.awt.BorderLayout.NORTH);

        add(taskDetailGridHolder, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnTextHolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel taskDetailGrid;
    private javax.swing.JPanel taskDetailGridHolder;
    private javax.swing.JLabel taskName;
    private javax.swing.JPanel taskNamePanel;
    // End of variables declaration//GEN-END:variables
}
