/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;
import Model.Task;
import java.awt.Dimension;
import db.UserDAO;
import javax.swing.JOptionPane;
import db.TaskDAO;
import Controller.BoardController;
import GUI.EditTask;
/**
 *
 * @author Kiwit
 */
public class TaskDetailDialogUpdated extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TaskDetailDialogUpdated.class.getName());
    private Task currentTask;
    /**
     * Creates new form TaskDetailDialog
     */
    public TaskDetailDialogUpdated(java.awt.Frame parent, boolean modal,Model.Task task) {
        super(parent, modal);
        this.currentTask = task; // Save the task globally wiill be recieved from task card click listener
        initComponents();
        Dimension fixedSize = new Dimension(400, 400); 

         this.setMinimumSize(fixedSize);
         this.setPreferredSize(fixedSize);
         this.setMaximumSize(fixedSize);

        UserDAO userDao = new UserDAO();
        
        System.out.println(task.getTaskName());
        TaskName.setText(task.getTaskName());
        ownerField.setText("Mitchell Travis"); //database missing owner field will be added in the future
        assignedField.setText(userDao.getUserNameById(task.getAssignedUser())); //update with actual user's name instead of their id
        ownerField.setText(userDao.getUserNameById(task.getOwner()));
        createdDateField.setText(task.getTimestamp());
        dueDateField.setText(task.getDueDate());
        descriptionField.setText(task.getTaskDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        TopPanel = new javax.swing.JPanel();
        TaskName = new javax.swing.JLabel();
        TaskDetailGrid = new javax.swing.JPanel();
        owner = new javax.swing.JLabel();
        ownerField = new javax.swing.JLabel();
        assignedLabel = new javax.swing.JLabel();
        assignedField = new javax.swing.JLabel();
        createdLabel = new javax.swing.JLabel();
        createdDateField = new javax.swing.JLabel();
        dueDateLabel = new javax.swing.JLabel();
        dueDateField = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionField = new javax.swing.JTextArea();
        btnContainer = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setModal(true);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 1, true));
        Main.setLayout(new java.awt.BorderLayout());

        TopPanel.setBackground(new java.awt.Color(255, 255, 255));
        TopPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        TopPanel.setLayout(new java.awt.BorderLayout());

        TaskName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TaskName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TaskName.setText("Task Name");
        TaskName.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TaskName.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        TopPanel.add(TaskName, java.awt.BorderLayout.CENTER);

        Main.add(TopPanel, java.awt.BorderLayout.PAGE_START);

        TaskDetailGrid.setBackground(new java.awt.Color(255, 255, 255));
        TaskDetailGrid.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        TaskDetailGrid.setMaximumSize(new java.awt.Dimension(400, 400));
        TaskDetailGrid.setLayout(new java.awt.GridLayout(5, 2, 10, 2));

        owner.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        owner.setText("Onwer");
        TaskDetailGrid.add(owner);

        ownerField.setText("Owner Name");
        TaskDetailGrid.add(ownerField);

        assignedLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        assignedLabel.setText("Assigned");
        TaskDetailGrid.add(assignedLabel);

        assignedField.setText("Assigned Name");
        TaskDetailGrid.add(assignedField);

        createdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createdLabel.setText("Created");
        TaskDetailGrid.add(createdLabel);

        createdDateField.setText("dd-mm-yyyy");
        TaskDetailGrid.add(createdDateField);

        dueDateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dueDateLabel.setText("Due Date:");
        TaskDetailGrid.add(dueDateLabel);

        dueDateField.setText("dd-mm-yyyy");
        TaskDetailGrid.add(dueDateField);

        description.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        description.setText("Description: ");
        TaskDetailGrid.add(description);

        descriptionField.setColumns(20);
        descriptionField.setRows(5);
        descriptionField.setEnabled(false);
        jScrollPane1.setViewportView(descriptionField);

        TaskDetailGrid.add(jScrollPane1);

        Main.add(TaskDetailGrid, java.awt.BorderLayout.CENTER);

        btnContainer.setBackground(new java.awt.Color(255, 255, 255));

        editBtn.setBackground(new java.awt.Color(0, 102, 255));
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.setMaximumSize(new java.awt.Dimension(45, 45));
        editBtn.setMinimumSize(new java.awt.Dimension(45, 23));
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });
        btnContainer.add(editBtn);

        deleteBtn.setBackground(new java.awt.Color(0, 102, 255));
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(this::deleteBtnActionPerformed);
        btnContainer.add(deleteBtn);

        Main.add(btnContainer, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(Main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // Show the confirmation first
    int response = JOptionPane.showConfirmDialog(this, 
        "Do you want to permanently delete this task?", 
        "Confirm Deletion", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);

    // Only proceed if they clicked 'Yes'
    if (response == JOptionPane.YES_OPTION) {
        // Create the DAO and call the delete method
        TaskDAO dao = new TaskDAO();
        boolean success = dao.deleteTask(currentTask.getTaskID());
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Task successfully removed.");
            if (BoardController.instance != null) {
            BoardController.instance.refreshBoard(); //refresh the board
        }
            this.dispose(); // Close the popup
        } else {
            JOptionPane.showMessageDialog(this, "Error: Could not delete from database.");
        }
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        // TODO add your handling code here:
        //gets the parent frame so another dialog can be opened
         java.awt.Frame parent = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
         
         EditTask editDialog = new EditTask(parent, true,this.currentTask);
    
         this.dispose();
         // Show the edit dialog
         editDialog.pack();
         editDialog.setLocationRelativeTo(parent);
         editDialog.setVisible(true);
         
    }//GEN-LAST:event_editBtnMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Main;
    private javax.swing.JPanel TaskDetailGrid;
    private javax.swing.JLabel TaskName;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JLabel assignedField;
    private javax.swing.JLabel assignedLabel;
    private javax.swing.JPanel btnContainer;
    private javax.swing.JLabel createdDateField;
    private javax.swing.JLabel createdLabel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel description;
    private javax.swing.JTextArea descriptionField;
    private javax.swing.JLabel dueDateField;
    private javax.swing.JLabel dueDateLabel;
    private javax.swing.JButton editBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel owner;
    private javax.swing.JLabel ownerField;
    // End of variables declaration//GEN-END:variables
}
